name: Docker Image CI

on: [push, pull_request]

jobs:

  make-flatpak:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pull the Docker Image
      run: docker pull adisuciu/scopy-flatpak-ubuntu20:latest
    - name: Run Docker Image
      run: |
            docker run --privileged \
                -v `pwd`:$GITHUB_WORKSPACE:rw \
                -e "GITHUB_WORKSPACE=$GITHUB_WORKSPACE" \
                adisuciu/scopy-flatpak-ubuntu20:latest /bin/bash -xe $GITHUB_WORKSPACE/ci/appveyor/inside_flatpak_docker.sh
    - uses: actions/upload-artifact@v2
      with:
        name: Scopy.flatpak
        path: ${{ github.workspace }}/Scopy.flatpak
    - name: Upload master flatpak build to continous prerelease
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      run: |
        wget https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_linux_amd64.tar.gz 
        tar xvf ghr_v0.13.0_linux_amd64.tar.gz
        ghr_v0.13.0_linux_amd64/ghr -u ${{ github.repository_owner }} -r scopy -name "Continuous build" -b "Latest succesful master build " -prerelease -debug -replace continous ${{ github.workspace }}/Scopy.flatpak
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

